### ISSUE TITLE
two warnings

### ISSUE THREAD

**Issue by masterkain** [nobrick/bitmex#4]
elixir 1.8.x, poison 4

```
remote: warning: module attribute @api_testnet_host was set but never used
remote:   lib/bitmex/rest/http_client.ex:9
remote:
remote: warning: function Poison.Parser.parse/1 is undefined or private. Did you mean one of:
remote:
remote:       * parse!/2
remote:
remote:   lib/bitmex/websocket/parser.ex:40
```

**Comment by nobrick** [comment]
The second warning seems to be caused by the undocumented API changes in poison 4.0. I've submitted a [PR](https://github.com/devinus/poison/pull/186) to it. Meanwhile, I'm updating bitmex to use `Poison.decode/1` for now instead of the removed function in `Poison.Parser`.
